# -*- coding: utf-8 -*-
"""DistanceDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17uNUoG9WHK4eedAbVf-4MyFZYRUy9REN
"""

# cd /path/to/desired/directory
# git clone https://github.com/Op27/distant-measurer-webcam.git
# cd distant-measurer-webcam
# pip install opencv-python ultralytics

import cv2
import math
from ultralytics import YOLO
from ultralytics.utils.plotting import colors

model = YOLO("yolov8s.pt")
cap = cv2.VideoCapture(0)

w, h, fps = (int(cap.get(x)) for x in (cv2.CAP_PROP_FRAME_WIDTH, cv2.CAP_PROP_FRAME_HEIGHT, cv2.CAP_PROP_FPS))

fps = 3.33

out = cv2.VideoWriter('output.avi', cv2.VideoWriter_fourcc(*'MJPG'), fps, (w, h))

center_point = (w // 2, h // 2)
pixel_per_meter =250

txt_color, txt_background, bbox_clr = ((0, 0, 0), (255, 255, 255), (255, 0, 255))

while True:
    ret, im0 = cap.read()
    if not ret:
        print("Video frame is empty or video processing has been successfully completed.")
        break

    results = model.track(im0, persist=True)
    boxes = results[0].boxes.xyxy.cpu()

    if results[0].boxes.id is not None:
        track_ids = results[0].boxes.id.int().cpu().tolist()

        if 1 not in track_ids:
            cv2.putText(im0, 'Distracted!', (20, 50), cv2.FONT_HERSHEY_SIMPLEX, 2,txt_color, thickness=2)
        else:
          for box, track_id in zip(boxes, track_ids):
              if track_id == 1:

                  x1, y1 = int((box[0] + box[2]) // 2), int((box[1] + box[3]) // 2)

                  distance = (math.sqrt((x1 - center_point[0]) ** 2 + (y1 - center_point[1]) ** 2))/pixel_per_meter

                  text_size, _ = cv2.getTextSize(f"Distance: {distance:.2f} m", cv2.FONT_HERSHEY_SIMPLEX,0.8, 2)
                  cv2.rectangle(im0, (int(box[0]), int(box[1] - text_size[1] - 6)), (int(box[0] + text_size[0] + 6), int(box[1]+1)), txt_background, thickness=-1)
                  cv2.putText(im0, f"Distance: {distance:.2f} m",(int(box[0]), int(box[1])), cv2.FONT_HERSHEY_SIMPLEX, 0.8,txt_color, thickness=2)

                  if distance > 0.7:
                      cv2.putText(im0, 'Distracted!', (20, 50), cv2.FONT_HERSHEY_SIMPLEX, 2,txt_color, thickness=2)
                  else:
                      cv2.putText(im0, 'No Distracted!!', (20, 50), cv2.FONT_HERSHEY_SIMPLEX, 2,txt_color, thickness=2)

    out.write(im0)
    cv2.imshow("visioneye-distance-calculation", im0)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break


out.release()
cap.release()
cv2.destroyAllWindows()